### ISSUE TITLE
Screen not updated.

### ISSUE THREAD

**Issue by ifs-pvt** [Pitchlyapp/meteor-apollo2#5]
OS: Windows 7.
Steps:
1. Cloned
2. Installed as per instruction
3. Started meteor - without issues
4. Opened localhost:3000 and saw "Current database value for this user" section with empty fields
5. Entered text fields and clicked "Update" - no result

**Comment by ifs-pvt** [comment]
Forgot: GraphiQL query returns default data:
{
  "data": {
    "person": {
      "id": "userid1",
      "name": "Michael Brook",
      "eyeColor": "brown",
      "occupation": "Programmer"
    }
  }
}

**Comment by michaelcbrook** [comment]
This is most likely due to this reported issue here: https://github.com/Pitchlyapp/meteor-apollo2/issues/4

Changes have been made that should hopefully resolve your issue, in particular, changing

`import Cache from 'apollo-cache-inmemory';`
to
`import { InMemoryCache } from 'apollo-cache-inmemory';`

and

`const cache = new Cache(window.__APOLLO_STATE);`
to
`const cache = new InMemoryCache(window.__APOLLO_STATE);`

This is because new versions of the NPM packages broke the previous way.
